graph LR
    A[Python] --> B[Aiogram]
    B --> BA[Redis FSM]
    C --> BA[Redis FSM]
    A --> C[Redis]
    A --> D[Docker]
    D --> AD[Dockerfile]
    D --> ADA[DockerHub]
    D --> DB[docker-compose]